name: container-test
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run script
        run: |
          ls -al /__w/example-python/
          ls -al /__w/example-python/example-python
          echo "meow"
          python script.py
