name: container-test
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run script
        run: |
          ls -al /__w/example-python/
          ls -al /__w/example-python/example-python
          echo "meow"
          python script.py

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@80df3c2668d854bcc8e8633dddde2942885200f8
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
